// Curated, hand-authored common words; this is not an exhaustive English dictionary.
export const WORDS = [...new Set(`
cat cot cog dog dot dat bat bad bed bet bit big bag bog bug bun but cut cup cap cop can car bar ban bin tin tan ten ton top tap tip sip sit sin sun son sob job joy toy tow row cow cod rod red rid rib rob bob mob mop map mad mat man men met net not hot hat hit hip hop pop pot pat pit pin pan pen pet peg pig fig fog log lot lit lid led leg lag lap lip rip rap rat ram rim run rum rug rag tag tug tan wet web wed win wit wig wag way day dry try cry fry fly ply shy why sky ski sea tea pea pie die tie lie age ace ice icy ink ant any art arm are ape apt ask ash aid air aim ate eat ear err era eye eel eve end hen her hey hay hid him his hum hug hog hut hip ivy ion inn ire ill imp jet jam jar jaw jug jig jog jot key kit kin keg kid lap lad law lay low lit let lee lie lip lug led log mud mug mum nut nod nap nag nip new now nor oak oar oat odd ode oil old one ore our out owe owl own pad pal paw pay per pew pin pig pod pry pub pun pup put red rot roe rub rut rye sad sag sap sat saw say set sew she sow sod sop son sum sup tab tar tax tea tee the thy toe too tot tub use van vat vet via vow war was wax wee win who won yes yet you zoo
cold cord card care core cure curt curl curd cut curd word ward warm worm work worn corn born bore bare barn burn turn torn tone tune tube cube cute mute mule male mole mold mild wild wilt tilt tile tide ride rude rule role rose rope ripe rise rice mice mine mint mind wind wine dine fine fire fare farm form foam roam room boom boot boat coat goat goal gold bold bald ball bell belt melt felt feet feed seed need heed head heat meat meet mete mate late date data dame same sane sand hand hard herd hero here hire wire wide tide time tame team tear pear peer peel pool poop poll pole pale sale salt sold sole soul sour tour four foul fool food good wood wool cool tool toll tall tail sail soil boil coil coin cone bone bond band bend tend tent tint tiny tidy city cite site side hide hole home come code mode more move love dove dive five file fill hill hall fall fail mail main pain rain raid road read reed lead load goad glow grow gray tray pray play plan clan clap slap slop shop shot slot slow snow show shoe shoo soot root roof hoof hood hold held help hemp camp lamp limp lime like lake lane land lend lent leaf lean loan moan mean bean bead beat boat boot book look lock lack luck duck dusk dust must mast most lost cost cast cash case cave save safe sage page rage race rack rock sock sick silk sink sing song long lone line lion loin join near fear rear year dear deer deep keep keen seen seem seam scam scan span spin skin skip slip ship chip chop crop drop drip trip trap wrap warp wasp rasp rash rush push bush lush lash last list fist fast past post pose nose note vote veto zero
act add ago all and awe axe bay bee bow box boy bus buy dam dew dim dip due duo ego elf elm fad fan fat fax fee few fix flu foe for fur gap gas gel gem get gig gin gum gun gut gym had ham has hem hoe how hue its lye may mom off orb ref six sub two urn vie yap yen zip mood moon noon soon cook hook took rook back pack peck pick puck kick neck sack hack dock deck disk desk task mask bask bark bank tank rank rink link wink pink punk junk sunk funk fun fond find fend fund fold ford fork pork port part park perk dark dart dirt hurt hunt runt rent rant rung rang ring king kind knee knew know knot knit next nest west best rest test text told toil toys soup soap soar scar star stir stub stun step stop spot spit spat spun swim swam swap snap snag smug snug drug drum dumb dump bump hump jump pump pulp gulf gull pull full dull doll doom dorm door poor pour hour your sure pure pare pair fair hair heir hail heal hope cope cake make rake take wake bake fake fame name game gave give gate gaze maze size wise wish fish dish dash dead deaf deal real seal meal mayo moat oats over oven open omen amen axes axis term germ firm film mill pill will well fell tell yell sell less loss boss moss mess mass miss kiss pass bass bath path math moth myth both foot loot loop hoop vast fact face pace cage cane done gone
wore ware
`.trim().split(/\s+/))].filter(w=>w.length===3||w.length===4);
export const PUZZLES=[{start:'cat',goal:'dog',label:'Cat → Dog',difficulty:'3 letters · warm-up'},{start:'cold',goal:'warm',label:'Cold → Warm',difficulty:'4 letters · classic'},{start:'head',goal:'tail',label:'Head → Tail',difficulty:'4 letters · stretch'},{start:'love',goal:'hate',label:'Love → Hate',difficulty:'4 letters · explore'},{start:'book',goal:'read',label:'Book → Read',difficulty:'4 letters · challenge'}];
WORDS.push('hate');
